db:
  image: postgres:9.4.4
web:
  build: .
  working_dir: /myapp
  command: bash -c "rm -f tmp/pids/server.pid && bundle && rake db:create && bundle exec rails s -p 3000 -b '0.0.0.0'"
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db
